resolver: lts-7.19
packages:
  - powerqueue
  - powerqueue-levelmem
  - powerqueue-distributed
  - powerqueue-sqs
extra-deps:
  - unagi-chan-0.4.0.0
  - timespan-0.3.0.0
  - amazonka-core-1.4.5
  - amazonka-1.4.5
  - amazonka-s3-1.4.5
  - amazonka-sqs-1.4.5
  - http-client-0.5.5
  - http-client-tls-0.3.3.1
  - http-conduit-2.2.3
  - aws-simple-0.4.0.0
